### ISSUE TITLE
无网络和请求出错

### ISSUE THREAD

**Issue by Leegeo-CN** [yfming93/FMListPlaceholder#1]
之前自己也写过这种，是通过黑魔法Method swizzling实现的，目前这个框架只能实现无数据一种情况吗？无网络和请求出错实现了吗？

**Comment by yfming93** [comment]
（如果需要点击刷新逻辑，可实现如下 block）
_tableView.reloadBlock = ^(UIScrollView *listView) {
  // Reload Handle is Here!
  // [listView.mj_header beginRefreshing]; // reloadData
};
在 如上 block 中自己掉调一下网络请求的方法，。如果想在 无网络和请求出错实现该占位图 ，就得自己在网络请求失败的 block 中调一下 列表的  reloadData 刷新。【核心是只要在网络请求方法中调了 reloadData 就会做是否显示占位图的逻辑处理。】
